---
- name: Copy and Extract beats into /tmp
  unarchive:
    src: /tmp/{{ beats }}-{{ version }}-linux-x86_64.tar.gz
    dest: /tmp/{{ beats }}-{{ version }}-linux-x86_64

- name: install beats type
  shell: rpm -ivh /tmp/{{ beats }}-{{ version }}-linux-x86_64.tar.gz

