---
- name: Copy and Extract beats into /tmp
  unarchive:
    src: /tmp/{{ beats }}-{{ version }}-linux-x86_64.tar.gz
    copy: yes
    dest: /tmp/

- name: untar file
  shell: tar -xvf /tmp/{{ beats }}-{{ version }}-linux-x86_64.tar

- name: install beats type
  shell: rpm -ivh /tmp/{{ beats }}-{{ version }}-linux-x86_64

