---
- name: Copy and Extract beats into /tmp
  copy:
    src: /tmp/{{ beats }}-{{ version }}-x86_64.rpm
    dest: /tmp/
    remote_src: no

- name: remove previous verison
  yum:
    name: metricbeat
    state: absent

- name: install beats type
  yum: 
    name: /tmp/{{ beats }}-{{ version }}-x86_64.rpm
    state: present

- name: copying over metricbeat.yml template
  template:
    src: metricbeat.j2
    dest: /etc/metricbeat/metricbeat.yml

- name: starting the metricbeat service
  service:
    name: "{{ type }}"beat
    state: started

- name: Enable service metricbeat after reboot.
  service:
    name: "{{ type }}"beat
    enabled: yes


