---
- name: Copy and Extract beats into /tmp
  copy:
    src: /tmp/{{ beats }}-{{ version }}-x86_64.rpm
    dest: /tmp/
    remote_src: no

- name: remove previous verison
  yum:
    name: metricbeat
    state: absent

#- name: install beats type
#  yum: 
#    name: /tmp/{{ beats }}-{{ version }}-x86_64.rpm

#- name:
#  template:
#    src: metricbeat.j2
#    dest: /etc/metricbeat/metricbeat.yml
