---
- name: Copy and Extract beats into /tmp
  copy:
    src: /tmp/{{ beats }}-{{ version }}-linux-x86_64.rpm
    dest: /tmp/

- name: install beats type
  shell: rpm -ivh /tmp/{{ beats }}-{{ version }}-linux-x86_64

