---
- name: Copy and Extract beats into /tmp
  copy:
    src: /tmp/{{ beats }}-{{ version }}-x86_64.rpm
    dest: /tmp/
    remote_src: no

- name: install beats type
  yum: 
    name: /tmp/{{ beats }}-{{ version }}-x86_64.rpm
